Sprint 13 Try 2
alexkiktev/java-shareit pull request #2
Opened 2023-03-07 00:59 UTC by alexkiktev

2023-03-07 06:13 UTC, Frilock requested changes
Доброе утро, оставил ряд комментариев к Вашей работе.

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserServiceImpl userService;
Нужно инжектить интерфейс, а не его реализацию, как минимум так будет проще писать тесты

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isBlank()) {
А text может быть null? Я бы предложил через StringUtils.isBlank проверять

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +@Component
Компонент и репозиторий дублируют друг друга, обе эти аннотации делают класс бином спринга.

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final HashMap<Long, Item> items;
Предложил бы Вам ее инициализировать, чтобы null нигде не было. Map... items = new HashMap..

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                if (item.getAvailable() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                .filter(i -> i.getName().toLowerCase().contains(text.toLowerCase()) ||
Можно использовать StringUtils.equalsIgnoreCase, будет выглядеть компактнее

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    public UserDto toUserDto(User user) {
Предлагаю у входного параметра проставить NonNull аннотацию от Jetbrains, которая бы показывала Вам, что сюда не может прийти нул, либо в методе проверять, что если объект нул то возвращать пустую ДТО или ошибку

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +@Component
Анналогично, Service и Component друг друга дублируют

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +@Slf4j
Логгер в данном классе не используется, либо используйте, либо удалите аннотацию

2023-03-07 06:13 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        for (Map.Entry<Long, User> mapEntries: users.entrySet()) {
Перед : пробел

2023-03-08 18:26 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    public UserDto toUserDto(User user) {
Спасибо, добавил зависимость, использовал NotNull (как понимаю, вы имели в виду эту аннотацию, в описании нет NonNull).

2023-03-08 19:25 UTC, Frilock approved these changes
Принято

2023-03-08 19:25 UTC, Frilock commented on pom.xml
> +			<version>24.0.1</version>
Версию в properties лучше =)

2023-03-09 00:41 UTC, alexkiktev commented on pom.xml
> +			<version>24.0.1</version>
Спасибо! Исправил.

2023-03-20 07:56 UTC, merged