ТЗ 14 первая итерация
alexkiktev/java-shareit pull request #4
Opened 2023-03-20 08:01 UTC by alexkiktev

2023-03-20 18:23 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе.

2023-03-20 18:23 UTC, Frilock commented on hs_err_pid9888.log
> +# There is insufficient memory for the Java Runtime Environment to continue.
.log классы должны отсутствовать на ревью. Добавьте их в .gitignore

2023-03-20 18:23 UTC, Frilock commented on pom.xml
> +			<version>${annotations.version}</version>
Лучше версию именовать как то так - jetbrains.annotations, вместо annotations

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public BookingItemInfoDto toBookingItemInfoDto(Booking booking) {
Тут вероятно тоже NotNull надо проставить

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
Схема паблик дефолтная, ее можно не указывать (идея подсвечивает серым).

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * " +
Довольно простые запросы, необходимо ли запрос делать через query?

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        getUser(userId);
В реальности Вы этот метод используете как проверку наличия данных в БД. Так и назовите метод existUserById. Иначе это вводит в заблуждение

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Данный набор значений конечен, предлагаю его вынести в enum. будет дополнительная валидация

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
Лишней вложенности можно избежать. Инвертируйте условие в if, затем бросьте исключение. оставшийся код можно будет писать без блока else

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            getLastAndNextBooking(itemOwnerDto);
Опять же используете get метод, однако возвращаемое значение никак не используется. Это неверно

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void getLastAndNextBooking(ItemOwnerDto itemOwnerDto) {
Менять данные по ссылке не особо хорошая идея. Лучше получайте оба данных и явно их проставляйте там где нужно, либо как минимум переименуйте метод

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        } else {
Лишняя вложенность, можно упростить

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Table(name = "users", schema = "public")
Значение схемы по умолчанию можно не указывать

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> -@RequiredArgsConstructor
Почему решили отказаться от данной аннотации?

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (userDto.getName() != null) {
Можно заменить на optional.ofNullable(...)

2023-03-20 18:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        List<User> users = userRepository.findAll();
Данный метод можно переписать с использованием stream API. Попробуйте, не получиться можете оставить так

2023-03-21 22:00 UTC, alexkiktev commented on hs_err_pid9888.log
> +# There is insufficient memory for the Java Runtime Environment to continue.
Готово

2023-03-21 22:31 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * " +
Действительно, запрос в методе findBookingsByItemId() довольно простой, но когда торопился, не удалось подобрать подходящее название метода. Сейчас исправил, добавил метод findBookingsByItemIdAndStatus.
Для метода findBookingsByItemIdAndBookerIdAndComplete() пробовал разные комбинации имени, но не удается подобрать правильные слова для условия по полю end_date. Оставил для него запрос через query.

2023-03-21 22:34 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        getUser(userId);
Спасибо, исправил

2023-03-21 22:36 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "select * " +
В findBookingsByItemIdAndBookerIdAndComplete() я хочу получить данные именно одним запросом, чтобы потом не добавлять фильтр по потоку.

2023-03-21 22:39 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(Status.APPROVED)) {
Спасибо, исправил.

2023-03-21 23:17 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Готово

2023-03-21 23:55 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            getLastAndNextBooking(itemOwnerDto);
Согласен, думаю, лучше будет название setLastAndNextBooking();

2023-03-22 00:09 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void getLastAndNextBooking(ItemOwnerDto itemOwnerDto) {
Переделал. Разделил на два метода, получаю объекты и присваиваю в методе, где был создан родительский объект.

2023-03-22 00:09 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            getLastAndNextBooking(itemOwnerDto);
Переделал. Разделил на два метода, получаю объекты и присваиваю в методе, где был создан родительский объект.

2023-03-22 00:16 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> -@RequiredArgsConstructor
Когда создавал BookingServiceImpl, забыл добавить эту аннотацию, соответственно, пришлось добавлять конструктор и @Autowired. Затем привел к одинаковому стилю все три класса.
Исправил, действительно же, работало раньше)

2023-03-22 00:22 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        List<User> users = userRepository.findAll();
Переписал.

2023-03-22 19:43 UTC, Frilock approved these changes
Работу принял, но вы не тот метод переименовали. Переименуйте на следующей итерации пожалуйста.

2023-03-22 19:43 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        getUser(userId);
Не там поправили, я просил переименовать метод не approvedBooking, а getUser.

2023-03-25 00:32 UTC, merged