Add item requests
alexkiktev/java-shareit pull request #5
Opened 2023-03-26 18:16 UTC by alexkiktev

2023-03-27 20:07 UTC, Frilock requested changes
Добрый вечер, нужно доделать тесты, плюс пара небольших комментариев.

2023-03-27 20:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/mapper/RequestMapper.java
> +@Service
Сюда более логичней подходит аннотация компонент

2023-03-27 20:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByBookerIdOrderByStartDesc(Long userId, Pageable pageParams);
Возвращайте в методах в которых с объектом pageble работаете, объект Page

2023-03-27 20:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    public List<RequestItemInfoDto> getRequestByUser(Long userId) {
Над переопределенными методами интерфейса отсутствует аннотация owweride

2023-03-27 20:07 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE)
А для чего уровень изоляции проставляете? В чем логика? Можно просто Transactional =)

2023-03-27 20:07 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void createBooking() {
Нужно доделать

2023-03-28 00:46 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE)
У меня при запуске всех тестов из класса UserServiceImplTest возникла проблема: когда тесты писал и запускал отдельно, они все работали, даже при запуске по несколько раз и друг за другом. Но когда запустил весь класс, перестали проходить тесты создания и обновления. Это происходило потому, что я ждал при проверке конкретно id = 1L, а после каждого теста транзакция хоть и окатывалась, но не сбрасывался автоинкремент id в таблице обратно на 1.
Я предположил, что нужно добавить изоляцию в проверяемый класс. Но в итоге это тоже не помогло и я добавил файл cleanup.sql, которым перед каждым тестом сбрасываю id во всех таблицах.
Саму изоляцию затем забыл убрать из UserServiceImpl.
Исправил.

2023-03-28 00:49 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    public List<RequestItemInfoDto> getRequestByUser(Long userId) {
Исправил

2023-03-28 00:59 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/request/mapper/RequestMapper.java
> +@Service
Почитал описание аннотаций, но, если честно, не понял, почему именно в этом классе лучше использовать @Component?
https://habr.com/ru/post/350682/
Как я понял, @Service - это псевдоним @Component, который используется в сервисном (бизнес-логике) слое.

@Component — это общий стереотип для любого компонента или компонента, управляемого Spring.
@Repository — это стереотип для персистентного слоя.
@Service — это стереотип для сервисного уровня.
@Controller — это стереотип для уровня представления (spring-MVC).

2023-03-28 01:58 UTC, alexkiktev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByBookerIdOrderByStartDesc(Long userId, Pageable pageParams);
А из самого сервисного класса в контроллер возвращать уже List, правильно понимаю?

2023-03-29 14:30 UTC, Frilock approved these changes
Добрый день, в целом принял, на Ваш вопрос постарался ответить

2023-03-29 14:30 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (bookings.isEmpty()) {
А сама коллекция null может быть? Когда сомневаетесь, можно использовать CollectionUtils.isEmpty

2023-03-29 14:30 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerMockMvcTest.java
> +    Long userId = 1L;
Смотрите, мне не очень такой код нравиться, на мой взгляд, лучше если бы вы объявили нужные для тестов поля, например, private Item item (у Вас отсутствует модификатор); 
А затем уже в методе c аннотацией beforeEach и AfterEach инициализировали поля (или создавали), а в AfterEach (если нужно - очищали).

2023-03-29 14:30 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/mapper/RequestMapper.java
> +@Service
Возможно это только мое восприятие, но лично я обычно ставлю Service только над классами с каким то бизнес кодом.

2023-04-02 06:48 UTC, merged